/**********************************************************************************************************************
 * \file ASCLIN_UART_mikroBUS.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#ifndef ASCLIN_UART_MIKROBUS_H_
#define ASCLIN_UART_MIKROBUS_H_

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void init_ASCLIN_UART_mikroBUS(void);                         /* Initialization function for mikroBUS UART   */
void send_receive_ASCLIN_UART_message_mikroBUS(void);         /* Send and receive function for mikroBUS UART */
void send_ASCLIN_UART_message_mikroBUS(void);                 /* Send function for mikroBUS UART             */
sint32 receive_buff_count_mikroBUS(void);                     /* Get receive buffer count for mikroBUS UART  */
void receive_ASCLIN_UART_message_mikroBUS(Ifx_SizeT cnt);     /* Receive function for mikroBUS UART          */
void send_command(uint8 i);

/*********************************************************************************************************************/
/*------------------------------------------------Global Variables----------------------------------------------------*/
/*********************************************************************************************************************/
extern uint8 g_rxRcvBuffer_mikroBUS[];                        /* Receive buffer for mikroBUS UART            */
extern int cnt_rcv_mikroBUS;                                  /* Receive counter for mikroBUS UART           */

#endif /* ASCLIN_UART_MIKROBUS_H_ */
