/**********************************************************************************************************************
 * \file ASCLIN_UART_mikroBUS.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_MIKROBUS_BAUDRATE           115200                                  

#define UART_MIKROBUS_PIN_RX             IfxAsclin1_RXA_P15_1_IN     /* mikroBUS RX pin (Pin 14) */
#define UART_MIKROBUS_PIN_TX             IfxAsclin1_TX_P15_0_OUT     /* mikroBUS TX pin (Pin 13) */

/* Definition of the interrupt priorities */
#define INTPRIO_ASCLIN1_RX      20
#define INTPRIO_ASCLIN1_TX      21

#define UART_MIKROBUS_RX_BUFFER_SIZE     64                                      
#define UART_MIKROBUS_TX_BUFFER_SIZE     64                                      
#define MIKROBUS_SIZE                    16                                      
#define MAX_RCV_BUFFER_SIZE_MIKROBUS     20

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declaration of the ASC handle */
static IfxAsclin_Asc g_ascHandle_mikroBUS;

/* Declaration of the FIFOs parameters */
static uint8 g_ascTxBuffer_mikroBUS[UART_MIKROBUS_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_ascRxBuffer_mikroBUS[UART_MIKROBUS_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

/* Definition of txData and rxData */
uint8 g_txData_mikroBUS[] = "mikroBUS Hello!";
uint8 g_rxData_mikroBUS[MIKROBUS_SIZE] = {''};
uint8 g_rxRcvBuffer_mikroBUS[MAX_RCV_BUFFER_SIZE_MIKROBUS] = {''};

/* Size of the message */
Ifx_SizeT g_count_mikroBUS = sizeof(g_txData_mikroBUS);

int cnt_rcv_mikroBUS = 0;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Adding of the interrupt service routines */
IFX_INTERRUPT(asclin1TxISR, 0, INTPRIO_ASCLIN1_TX);
void asclin1TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_ascHandle_mikroBUS);
}

IFX_INTERRUPT(asclin1RxISR, 0, INTPRIO_ASCLIN1_RX);
void asclin1RxISR(void)
{
    Ifx_SizeT size_of_read = 1;
    IfxAsclin_Asc_isrReceive(&g_ascHandle_mikroBUS);
    IfxAsclin_Asc_read(&g_ascHandle_mikroBUS, g_rxData_mikroBUS, &size_of_read, TIME_INFINITE);

    for(int i=0 ; i < MAX_RCV_BUFFER_SIZE_MIKROBUS-1; i++)
    {
        g_rxRcvBuffer_mikroBUS[i] = g_rxRcvBuffer_mikroBUS[i+1];
    }
    g_rxRcvBuffer_mikroBUS[MAX_RCV_BUFFER_SIZE_MIKROBUS-1] = g_rxData_mikroBUS[0];
    cnt_rcv_mikroBUS++;
}

/* This function initializes the ASCLIN UART module for mikroBUS */
void init_ASCLIN_UART_mikroBUS(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN1);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = UART_MIKROBUS_BAUDRATE;

    /* Disable loopback for external communication */
    ascConfig.loopBack = FALSE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN1_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN1_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_ascTxBuffer_mikroBUS;
    ascConfig.txBufferSize = UART_MIKROBUS_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_ascRxBuffer_mikroBUS;
    ascConfig.rxBufferSize = UART_MIKROBUS_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,                IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &UART_MIKROBUS_PIN_RX,   IfxPort_InputMode_pullUp,     /* RX pin           */
        NULL_PTR,                IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &UART_MIKROBUS_PIN_TX,   IfxPort_OutputMode_pushPull,  /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_ascHandle_mikroBUS, &ascConfig);
}

/* This function sends and receives message via mikroBUS */
void send_receive_ASCLIN_UART_message_mikroBUS(void)
{
    IfxAsclin_Asc_write(&g_ascHandle_mikroBUS, g_txData_mikroBUS, &g_count_mikroBUS, TIME_INFINITE);
    IfxAsclin_Asc_read(&g_ascHandle_mikroBUS, g_rxData_mikroBUS, &g_count_mikroBUS, TIME_INFINITE);
}

void send_ASCLIN_UART_message_mikroBUS(void)
{
    IfxAsclin_Asc_write(&g_ascHandle_mikroBUS, g_txData_mikroBUS, &g_count_mikroBUS, TIME_INFINITE);
}

sint32 receive_buff_count_mikroBUS(void)
{
    return cnt_rcv_mikroBUS;
}

void receive_ASCLIN_UART_message_mikroBUS(Ifx_SizeT cnt)
{
    IfxAsclin_Asc_read(&g_ascHandle_mikroBUS, g_rxData_mikroBUS, &cnt, TIME_INFINITE);
}

void send_command(uint8 i)
{
    Ifx_SizeT g_count_cmd_protocal = 4;
    uint8 cmd_protocal[4] = {'#', 'c','*',' '};

    cmd_protocal[2] = i;

    IfxAsclin_Asc_write(&g_ascHandle_mikroBUS, cmd_protocal, &g_count_cmd_protocal, TIME_INFINITE);
}
